name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name : Navigate to aloas-website folder 
      run : | 
        cd aloas-website
    - name: Install dependencies and build
      run: |
        cd aloas-website
        ls
        npm install
        npm ci
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 149.202.51.120
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY}}
        script: |
          ssh ubuntu@149.202.51.120 'mkdir -p /var/www/$VUE_JS_APP_NAME'
          scp -r dist/* ubuntu@149.202.51.120:/var/www/$VUE_JS_APP_NAME/
          ssh ubuntu@149.202.51.120 'cd /var/www/$VUE_JS_APP_NAME && npm ci && pm2 restart all'
