name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm ci
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.GITHUB_TOKEN}}
        script: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'mkdir -p /var/www/$VUE_JS_APP_NAME'
          scp -r dist/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/$VUE_JS_APP_NAME/
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'cd /var/www/$VUE_JS_APP_NAME && npm ci && pm2 restart all'
