name: Deploy to Ubuntu VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd aloas-website
          npm ci

      - name: Build
        run: |
          cd aloas-website
          npm run build

      - name: Create directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html/aloas-website
            sudo chown -R ${{ secrets.SERVER_USERNAME }}:$USER /var/www/html/aloas-website
            sudo chmod -R 755 /var/www/html/aloas-website

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: aloas-website/dist/
          target: /var/www/html/aloas-website

   
      - name: SSH into VPS and restart application with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/aloas-website
            npm install pm2 -g
            pm2 delete my-app || true
            pm2 start npm --name "my-app" -- start
